export const AUTH_UPDATE_FIELD = 'AUTH_UPDATE_FIELD';
export const ASYNC_UPDATE_FIELD = 'ASYNC_UPDATE_FIELD';
export const TIMETABLE_UPDATE_FIELD = 'TIMETABLE_UPDATE_FIELD';
export const DAYS_UPDATE_FIELD = 'DAYS_UPDATE_FIELD';
export const PERIODS_UPDATE_FIELD = 'PERIODS_UPDATE_FIELD';
export const SUBJECTS_UPDATE_FIELD = 'SUBJECTS_UPDATE_FIELD';
export const TEACHERS_UPDATE_FIELD = 'TEACHERS_UPDATE_FIELD';
export const YEARS_UPDATE_FIELD = 'YEARS_UPDATE_FIELD';
export const ACTIVITIES_UPDATE_FIELD = 'ACTIVITIES_UPDATE_FIELD';
export const SAVE_TIMETABLE = 'SAVE_TIMETABLE';
export const SAVE_TIMETABLE_AUTH = 'SAVE_TIMETABLE_AUTH';


export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const ISLOGGEDIN = 'ISLOGGEDIN';



export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
