export const AUTH_UPDATE_FIELD = 'AUTH_UPDATE_FIELD';
export const ASYNC_UPDATE_FIELD = 'ASYNC_UPDATE_FIELD';
export const TIMETABLE_UPDATE_FIELD = 'TIMETABLE_UPDATE_FIELD';
export const DAYS_UPDATE_FIELD = 'DAYS_UPDATE_FIELD';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const ISLOGGEDIN = 'ISLOGGEDIN';



export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
