export const AUTH_UPDATE_FIELD = 'AUTH_UPDATE_FIELD';
export const ASYNC_UPDATE_FIELD = 'ASYNC_UPDATE_FIELD';
export const TIMETABLE_UPDATE = 'TIMETABLE_UPDATE';
export const LIST_TIMETABLE_UPDATE_FIELD = 'LIST_TIMETABLE_UPDATE_FIELD';
export const TIMETABLE_UPDATE_FIELD = 'TIMETABLE_UPDATE_FIELD';
export const PERIODS_UPDATE_FIELD = 'PERIODS_UPDATE_FIELD';
export const SUBJECTS_UPDATE_FIELD = 'SUBJECTS_UPDATE_FIELD';
export const TEACHERS_UPDATE_FIELD = 'TEACHERS_UPDATE_FIELD';
export const STUDENTS_UPDATE_FIELD = 'STUDENTS_UPDATE_FIELD';
export const TAGS_UPDATE_FIELD = 'TAGS_UPDATE_FIELD';
export const ACTIVITIES_UPDATE_FIELD = 'ACTIVITIES_UPDATE_FIELD';
export const BUILDINGS_UPDATE_FIELD = 'BUILDINGS_UPDATE_FIELD';
export const ROOMS_UPDATE_FIELD = 'ROOMS_UPDATE_FIELD';
export const SPACE_CONSTRAINT_UPDATE_FIELD = 'SPACE_CONSTRAINT_UPDATE_FIELD';
export const FINAL_TIMETABLE_ORDER_UPDATE_FIELD = 'FINAL_TIMETABLE_ORDER_UPDATE_FIELD';

export const SAVE_TIMETABLE = 'SAVE_TIMETABLE';
export const SEND_TIMETABLE = 'SEND_TIMETABLE';
export const EXPORT_TIMETABLE = 'EXPORT_TIMETABLE';
export const RECEIVE_TIMETABLE = 'RECEIVE_TIMETABLE';
export const NEW_TIMETABLE = 'NEW_TIMETABLEE';
export const LIST_TIMETABLES = 'LIST_TIMETABLES';
export const SAVE_TIMETABLE_AUTH = 'SAVE_TIMETABLE_AUTH';


export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const ISLOGGEDIN = 'ISLOGGEDIN';
export const GENERATE_NEW_KEY = 'GENERATE_NEW_KEY';



export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
